apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
        name: front-pod
        admission.datadoghq.com/enabled: "true"
      annotations:
        ad.datadoghq.com/web.logs: '[{"source": "front","service": "front-edge","tags": ["env:prod"]}]'
    spec:
      containers:
        - name: web
          image: gcr.io/or1g1n-186209/front-image:195aeba4
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: front-config
            - secretRef:
                name: front-secrets
          resources:
            requests:
              cpu: 200m
              memory: 256Mi

      imagePullSecrets:
        - name: gcr-json-key
