apiVersion: v1
kind: Service
metadata:
  name: connectors-edge-service
spec:
  selector:
    app: connectors-edge
    name: connectors-edge-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  type: ClusterIP
