name: Lint (xp1)

on:
  push:
    paths:
      - xp1/**
      - .github/workflows/lint-xp1.yml

jobs:
  check-eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          cache: "npm"
          cache-dependency-path: ./xp1/package-lock.json
      - working-directory: xp1
        run: npm install && npm run lint && npm run format:check
